### ISSUE TITLE
Time complexity of algorithm in check_for_missing_repos() is O(n^2)

### ISSUE THREAD

**Issue by msekletar** [rh-lab-q/remote-dependency-solving#103]
I know that arrays we deal with in this case are not going to be huge so this probably isn't pressing issue. Nevertheless, I think code could be improved by sorting array of local repos  using `qsort` after it is populated and then nested `for` loop may be replaced by call to `bsearch`. 

In case you don't want to bother with rewrite, then at least note the following.

Current code contains a bug, because `found` variable is not reset back to zero on next iteration of outer `for` loop.

One more issue with current code is this weird `if` statement,

``` C
 if ((strlen(req_repos[i1]) == strlen(local_repos[i2])) && (strncmp(req_repos[i1], local_repos[i2], strlen(req_repos[i1])) == 0))
```

I think that second check implies the first (i.e. if strings are equal, they must have same length), hence first part of `&&` expression is redundant. I'd use simply use `strcmp` in this case.

**Comment by jozkar** [comment]
Thank you for your suggestion. We'll look at it.
