### ISSUE TITLE
Use /etc/os-release to figure out Fedora version

### ISSUE THREAD

**Issue by msekletar** [rh-lab-q/remote-dependency-solving#95]
I just noticed that module `src/common/util.c` implements very fragile scheme to figure out Fedora release. Implemented scheme probably doesn't work with kernels which are not built by distribution, thus kernel release doesn't contain fcXX part. Please consider using /etc/os-release as the source of this information.

**Comment by mruprich** [comment]
Thank you, we will fix this asap.
